using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class GameManager : MonoBehaviour
{
    public static GameManager instance;
    public bool isGameover = false;
    public Text scoreText;
    public GameObject gameoverUI;
    private int score = 0;
    void Awake()
    {
        if (instance == null) instance = this;
        else
        {
            Debug.LogWarning("두 개 이상의 게임매니저가 존재합니다!");
            Destroy(gameObject);
        }
    }

    void Update()
    {
        if (isGameover && Input.GetKeyDown(KeyCode.R))
        {
            SceneManager.LoadScene("Desert");
        }
        if (isGameover && Input.GetKeyDown(KeyCode.Q))
        {
            Application.Quit();
        }

    }

    public void AddScore(int newScore)
    {
        score += newScore;
        if(score < 0)
        {
            OnPlayerDead();
        }
        scoreText.text = "Score : " + score;
    }

    public void OnPlayerDead()
    {
        isGameover = true;
        gameoverUI.SetActive(true);
    }
}
